version: "3"

services:
    database:
        image: postgres:12
        container_name: database
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: CarService
        ports:
            - 5432:5432
        networks:
            - backend
    carservice-backend:
        build: 
            context: .
            dockerfile: Dockerfile-SpringBoot
        image: carservice_springboot_backend
        container_name: carservice_backend
        command: ["java", "-jar", "./opt/CarService-Backend/target/CarService-1.2.0.jar"]
        depends_on:
            - database
        networks:
            - backend
            - frontend
        ports:
            - 8080:8080
        expose:
            - 8080
    carservice-frontend:
        build: 
            context: .
            dockerfile: Dockerfile-Angular
        image: carservice_angular_frontend
        container_name: carservice_frontend
        depends_on: 
            - carservice-backend
        networks: 
            - frontend
        ports:
            - 80:80
networks:
    backend:  
    frontend: