{
 "title": "CarService-Backend-Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Hit"
    },
    {
     "expr": "pg_stat_database_blks_read{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"} ",
     "legendFormat": "Read"
    },
    {
     "expr": "pg_stat_database_conflicts{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "pg_stat_database_numbackends{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Connections Backend"
    },
    {}
   ]
  },
  {
   "title": "Datanase Tup Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "pg_stat_database_tup_fetched{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Fetched"
    },
    {
     "expr": "pg_stat_database_tup_inserted{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Inserted"
    },
    {
     "expr": "pg_stat_database_tup_returned{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Returned"
    },
    {
     "expr": "pg_stat_database_tup_updated{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "pg_stat_database_xact_commit{datid=\"16384\",datname=\"CarService\",server=\"database.default:5432\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_database_size{datname=\"CarService\",server=\"database.default:5432\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "process_uptime_seconds ", "legendFormat": "Uptime " }
   ]
  },
  {
   "title": "Live Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live Threads" }
   ]
  },
  {
   "title": "JVM Live Deamon Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_threads_daemon_threads ", "legendFormat": "Live Deamon Threads" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "system_cpu_count", "legendFormat": "CPU Cores" }
   ]
  },
  {
   "title": "LOG4J2 Logs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "log4j2_events_total{level=\"info\"}",
     "legendFormat": "Info"
    },
    {
     "expr": "log4j2_events_total{level=\"error\"}",
     "legendFormat": "Error"
    },
    {
     "expr": "log4j2_events_total{level=\"trace\"}",
     "legendFormat": "Trace"
    },
    {
     "expr": "log4j2_events_total{level=\"warn\"}",
     "legendFormat": "Warn"
    },
    {
     "expr": "log4j2_events_total{level=\"fatal\"}",
     "legendFormat": "Fatal"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "Systen CPU Usage" },
    { "expr": "process_cpu_usage", "legendFormat": "Process CPU Usage" }
   ]
  },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "Average System Load 1m" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jdbc_connections_active", "legendFormat": "Current Database Connections" },
    {}
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "JVM Thread States",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{state=\"runnable\",}",
     "legendFormat": "runnable"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"waiting\",}",
     "legendFormat": "waiting"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"blocked\",}",
     "legendFormat": "blocked"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"timed-waiting\",}",
     "legendFormat": "timed-waiting"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"new\",}",
     "legendFormat": "new"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"terminated\",}",
     "legendFormat": "terminated"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"Tenured Gen\"}",
     "legendFormat": "Heap | Tenured Gen"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"Eden Space\"}",
     "legendFormat": "Heap | Eden Space"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"Survivor Space\"}",
     "legendFormat": "Heap | Survivor Space"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\",id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "NonHeap | profiled nmethods"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\",id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "NonHeap | non-profiled nmethods"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\",id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "NonHeap | non-nmethods"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\",id=\"Compressed Class Space\"}",
     "legendFormat": "NonHeap | Compressed Class Space"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP 200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/car/list\"}",
     "legendFormat": "GET | CarList"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"PUT\",outcome=\"SUCCESS\",status=\"200\",uri=\"/car/edit\"}",
     "legendFormat": "PUT | EditCar"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/car/list/{id}\"}",
     "legendFormat": "GET | CarList by ID"
    }
   ]
  },
  {
   "title": "HTTP 201",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"POST\",outcome=\"SUCCESS\",status=\"201\",uri=\"/car/create\"}",
     "legendFormat": "POST | CreateCar"
    }
   ]
  },
  {
   "title": "HTTP 204",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"DELETE\",outcome=\"SUCCESS\",status=\"204\",uri=\"/car/delete\"}",
     "legendFormat": "DELETE | Car"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"DELETE\",outcome=\"SUCCESS\",status=\"204\",uri=\"/car/deleteAll\"}",
     "legendFormat": "DELETE | ALL"
    }
   ]
  },
  {
   "title": "HTTP 404",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"GET\",status=\"404\",uri=\"/car/list\"}",
     "legendFormat": "GET | ListCar"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"GET\",status=\"404\",uri=\"/car/list/{id}\"}",
     "legendFormat": "GET | ListCar by ID"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"PUT\",status=\"404\",uri=\"/car/edit\"}",
     "legendFormat": "PUT | EditCar"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"DELETE\",status=\"404\",uri=\"/car/delete\"}",
     "legendFormat": "DELETE | Car"
    }
   ]
  },
  {
   "title": "HTTP 400",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"DELETE\",status=\"400\",uri=\"/car/delete\"}",
     "legendFormat": "DELETE | Car"
    },
    {
     "expr": "http_server_requests_seconds_count{method=\"PUT\",status=\"400\",uri=\"/car/edit\"}",
     "legendFormat": "PUT | EditCar"
    }
   ]
  }
 ]
}