apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: carservice-backend
    release: prometheus-monitoring
  name: backend-service-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    path: "/actuator/prometheus"
    port: springboot
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: carservice-backend
