# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CarService-API-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Local PostgreSQL Server
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: 'CarService'
        postgresql user: 'postgres'
        postgresql password: 'admin'
    - name: Changing Hostfile for Springboot
      run:  sudo echo "127.0.0.1 database" | sudo tee -a /etc/hosts      
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
    - name: test
      uses: actions/setup-node@v2   
      with:
          node-version: '12'
    - run: |
        java -jar ./target/CarService-1.2.0.jar
        newman run ./Tests/CarService.postman_collection.json -e ./Tests/local.postman_environment.json