# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CarService-Angular-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Node.js (15) Testing Angular App
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - run: cd ./CarService-FrontEnd && npm ci
    - run: cd ./CarService-FrontEnd && npm run build:prod --if-present
    - run: cd ./CarService-FrontEnd && npm run test:prod
